### ISSUE TITLE
Change use of search-index API to fit latest version

### ISSUE THREAD

**Issue by eklem** [eklem/search-index-indexer#10]
Figure out the [change in the `search-index` API](https://github.com/fergiemcdowall/search-index/issues/265), and do the necessary changes in index.js.

**Comment by fergiemcdowall** [comment]
As far as I can remember, it is only the constructor that has changed.

From now on, API changes are going to be included in release notes

**Comment by fergiemcdowall** [comment]
constructor is now:

``` javascript
require('search-index')(options, function(err, si) {
  // do stuff with si
});
```

**Comment by eklem** [comment]
:+1: Thank you!

**Comment by eklem** [comment]
It's the same as before (0.7.6), but with the debug messages, it takes for ever to finish indexing a batch, so thought it was looping something. Set the logLevel to warn to mute it for now, and closing.
