### ISSUE TITLE
Batch size option

### ISSUE THREAD

**Issue by eklem** [eklem/search-index-indexer#13]
Default batch size is the full batch you're feeding the indexer, but it should be possible to set something else, when you experience that the indexer runs out of memory and crashes.

Most probably, this will be fixed in the `search-index-adder` at some point, but good to have a little more control.

**Comment by eklem** [comment]
@fergiemcdowall How do I do this best? I want to do the indexing in batches, waiting for [n] amount of items to index before I go on the next batch.

**Comment by fergiemcdowall** [comment]
At the moment you pass an array of documents, so you are setting the size of the array (batch) yourself. 

(I am just about to implement a `writeStream` endpoint in the API which will take a neverending stream of objects which `search-index` will internally spilt into chunks to be indexed- at that point default batch size will be a config param)

**Comment by eklem** [comment]
Cool! Just what I need. I was more thinking of how to do it in node.js since async and callbacks is not my strong side.

**Comment by eklem** [comment]
Would that endpoint with config param be exposed through `norch` too?

**Comment by eklem** [comment]
Making this a little different. This is for testing. Will add two flags:

``` console
  -s --start [number]
  -e --end [number]
```

They'll be used to slice the array that is indexed.
